"""
Django settings for aims project.

Generated by 'django-admin startproject' using Django 1.8.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '(rrza$y^**w=h1(4v*mv6k=*b!lf&pz)338(4pq!_9yo3-km73'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = (
    # TODO: organize installed apps
    'grappelli',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'django.contrib.sites',
    'filetransfers',
    'bootstrap3',
    'aims',
    'home',
    'data_entry',
    'management',
    'django_filters',
    'reports',
    'help',
    'profiles',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'aims.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.core.context_processors.request',
            ],
        },
    },
]

WSGI_APPLICATION = 'aims.wsgi.application'

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Nairobi'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'static')

MEDIA_ROOT = os.path.join(BASE_DIR, 'documents')

MEDIA_URL = '/files/'

LOGIN_URL = '/login/'

LOGIN_REDIRECT_URL = '/login_success/'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.contrib.auth.context_processors.auth',
                'django.template.context_processors.debug',
                'django.template.context_processors.i18n',
                'django.template.context_processors.media',
                'django.template.context_processors.static',
                'django.template.context_processors.tz',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# Login Settings
LOGIN_URL = '/login/'


# Module settings
CURRENCY_ABBREVIATION_LENGTH = 3
DOCUMENT_UPLOAD_DIR = os.path.join(BASE_DIR, 'documents')
GRAPPELLI_ADMIN_TITLE = 'Somali AIMS'

# SendGrid Settings
EMAIL_BACKEND = "sgbackend.SendGridBackend"
SENDGRID_USER = "somaliaims"
SENDGRID_PASSWORD = "aims.somali1"

# Modify to use postgresql for production
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'somaliaims',
        'USER': 'somaliaims',
        'PASSWORD': 'aims.somali',
        'HOST': 'localhost',
    }
}

ADMIN_URL = '/admin/'
DATA_ENTRY_URL = '/data-entry/'
MANAGEMENT_URL = '/management/'

try:
    if DEBUG:
        from .local_settings import *
except ImportError:
    pass

SITE_ID = 1

BOOLEAN_CHOICES = (
    (None, ' '),
    (True, 'Yes'),
    (False, 'No')
)

SDRF_SSA_CHOICES = (
    (None, ' '),
    ('WB Multi-Partner Fund (MPF)', 'WB Multi-Partner Fund (MPF)'),
    ('UN Multi-Partner Trust Fund (MPTF)', 'UN Multi-Partner Trust Fund (MPTF)'),
    ('African Development Bank Multi-Partner Programme (AMPP)',
     'African Development Bank Multi-Partner Programme (AMPP)'),
    ('Special Financing Facility (SFF)', 'Special Financing Facility (SFF)'),
    ('Somalia Stability Fund (SSF)', 'Somalia Stability Fund (SSF)'),
    ('Not using SDRF', 'Not using SDRF'),
)

FUNDING_INSTRUMENTS = (
    (None, ' '),
    ('General Budget Support', 'General Budget Support'),
    ('Sector Budget Support', 'Sector Budget Support'),
    ('Pooled fund', 'Pooled fund'),
    ('Project/program', 'Project/program')
)

FUNDING_CHANNELS = (
    (None, ' '),
    ('Channel 1', 'Channel 1'),
    ('Channel 2', 'Channel 2'),
    ('Channel 3', 'Channel 3')
)

MULTIFIELD_CHOICES = (
    (None, ' '),
    ('Principal', 'Principal'),
    ('Significant', 'Significant'),
    ('Not targeted', 'Not targeted'),
    ('NA', 'NA')
)

SENSITIVITY_ANALYSIS_CHOICES = (
    (None, ' '),
    ('Conflict analysis conducted and updated regularly', 'Conflict analysis conducted and updated regularly'),
    ('Conflict analysis conducted once but not updated', 'Conflict analysis conducted once but not updated'),
    ('No conflict analysis conducted for activity', 'No conflict analysis conducted for activity')
)





